=== SamuelGarciaIESBelen/1DAW/Lenguajes de marcas/XML/Repaso Examen/XML-Schema/Puertos/puertos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="tipo_cadenabarco">
        <xs:restriction base="xs:string">
            <xs:pattern value="B[0-9]{4,6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipo_codigobarco">
        <xs:simpleContent>
            <xs:extension base="tipo_cadenabarco">
                <xs:attribute name="paÃ­s" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="tipo_codigosalida">
        <xs:restriction base="xs:string">
            <xs:enumeration value="01"/>
            <xs:enumeration value="49"/>
            <xs:enumeration value="DESC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipo_tasas">
        <xs:restriction base="xs:string">
            <xs:length value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="movimientos">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="entrada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigobarco" type="tipo_codigobarco"/>
                            <xs:element name="origen" type="xs:string"/>
                            <xs:element name="pasa_por" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="destino" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="salida">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigobarco" type="tipo_codigobarco"/>
                            <xs:element name="tasaspagadas" type="tipo_tasas" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="tipo_codigosalida" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== SamuelGarciaIESBelen/1DAW/Lenguajes de marcas/XML/Repaso Examen/XML-Schema/Puertos/puertos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--El elemento raíz es movimientos y siempre lleva un atributo fecha-->
	<movimientos fecha="2022-03-01"
				xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
				xs:noNamespaceSchemaLocation="puertos.xsd">
		<!--Dentro de movimiento hay infinitos elementos "entrada" o
			"salida" que pueden repetirse y/o ir en cualquier orden-->
		<entrada>
			<!--El codigo de barco siempre lleva un atributo "país"
				que contiene cadenas. El codigo de barco siempre es
				una B seguida un número de entre 4 y 6 cifras-->
			<codigobarco país="Panamá">B0143</codigobarco>
			<!--Siempre hay un elemento origen que acepta cadenas-->
			<origen>Atenas</origen>
			<!--Puede haber 0 o muchos elementos "pasa_por" y que
			lleva dentro cadenas-->
			<pasa_por>Algeciras</pasa_por>
			<pasa_por>Oporto</pasa_por>
			<!--Siempre hay un destino que lleva dentro cadenas-->
			<destino>Amberes</destino>
		</entrada>
		<!--La salida siempre lleva un codigo que puede ser "01",
			"49" o "DESC"-->
		<salida codigo="01">
			<codigobarco>B0143</codigobarco>
			<!--Puede llevar o no un elemento VACÍO llamado
				"tasaspagadas"-->
			<tasaspagadas/>
		</salida>
	</movimientos>
