=== SamuelGarciaIESBelen/1DAW/Lenguajes de marcas/XML/XML-Schema/XML Schema/cine.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="cine">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="pelicula" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="pelicula">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="titulo" type="xsd:string"/>
                <xsd:element name="director" type="xsd:string"/>
                <xsd:element ref="estreno"/>
                <xsd:element ref="reparto" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="estreno" type="xsd:date"></xsd:element>
    <xsd:element name="reparto" type="xsd:string"></xsd:element>
</xsd:schema>

=== SamuelGarciaIESBelen/1DAW/Lenguajes de marcas/XML/XML-Schema/XML Schema/cine(xmlSchema).xml
<?xml version="1.0" encoding="UTF-8"?>

<cine xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsd:noNamespaceSchemaLocation="cine.xsd">
	<pelicula>
		<titulo>Mad Max</titulo>
		<director>George Miller</director>
		<estreno>15 mayo 2015</estreno>
		<reparto>Tom Hardy</reparto>
		<reparto>Charlize Theron</reparto>
		<reparto>Nicholas Hoult</reparto>
	</pelicula>
	<pelicula>
		<titulo>Inside Out</titulo>
		<director>Pete Docter</director>
		<estreno>17 junio 2015</estreno>
		<reparto>Amy Poehler</reparto>
		<reparto>Phyllis Smith</reparto>
		<reparto>Bill Hader</reparto>
	</pelicula>
</cine>
